name: Clang Linux CI v2
on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  #schedule:
    #- cron:  '* 0 * * *'

  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
jobs:
  kick_tuxbuild:
    name: Kick Off Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create jobs
        run: |
          ls -l foo.sh
          ./foo.sh > output.txt
      - name: save output
        uses: actions/upload-artifact@v2
        with:
          path: output.txt
          name: output_artifact
  # Example using 3D matrix.
  fetch_and_boot:
    runs-on: ubuntu-latest
    # Waits on kick_tuxbuild to complete.
    needs: kick_tuxbuild
    strategy:
      matrix:
        ARCH: [x86_64, arm64]
        LLVM: [0, 1]
        LLVM_IAS: [0, 1]
    env:
      ARCH: ${{ matrix.ARCH }}
      LLVM: ${{ matrix.LLVM }}
      LLVM_IAS: ${{ matrix.LLVM_IAS }}
    name: ARCH=${{ matrix.ARCH }} LLVM=${{ matrix.LLVM }} LLVM_IAS=${{ matrix.LLVM_IAS }}
    steps:
      - uses: actions/checkout@v2
        submodules: true
      - uses: actions/download-artifact@v2
        with:
          name: output_artifact
      - name: Boot Test
        run: ./check_logs.py
  # Example without matrix.
  fetch_and_boot_non_matrix:
    runs-on: ubuntu-latest
    needs: kick_tuxbuild
    name: ARCH=riscv LLVM=1 LLVM_IAS=1
    env:
      ARCH: riscv
      LLVM: 1
      LLVM_IAS: 1
    steps:
      - uses: actions/checkout@v2
        submodules: true
      - uses: actions/download-artifact@v2
        with:
          name: output_artifact
      - name: Boot Test
        run: ./check_logs.py
  # Copy me to add a new target, fill in ???j
  #template:
    #runs-on: ubuntu-latest
    #needs: kick_tuxbuild
    #name: ARCH=??? LLVM=??? LLVM_IAS=???
    #env:
      #ARCH: ???
      #LLVM: ???
      #LLVM_IAS: ???
    #steps:
      #- uses: actions/checkout@v2
      #- uses: actions/download-artifact@v2
        #with:
          #name: output_artifact
      #- name: Boot Test
        #run: ./bar.sh
